version: "3.8"

services:
  ustmongo:
    image: mongo:latest
    container_name: ustmongo
    restart: always
    ports:
      - 0.0.0.0:27017:27017
  uustdocker:
    build: ./u-ust
    image: u-ust-docker
    container_name: uustdocker
    ports:
      - 0.0.0.0:2021:2021
    depends_on:
      - ustmongo
  ui-angular:
    build: ./client
    container_name: ui-angular
    ports:
      - 0.0.0.0:4200:4200
    depends_on:
      - uustdocker
